### ISSUE TITLE
Should InjectingFragment inject itself onActivityCreated instead?

### ISSUE THREAD

**Issue by soapsign** [adennie/fb-android-dagger#16]
Due to the fact that onAttach does not guarantee the Activity has finished its onCreate, so the activity object graph the injecting fragment get might be null.
So I think it is not safe to inject dependency on onAttach method.

**Comment by adennie** [comment]
The Activity's onCreate should call super.onCreate (which builds the Activity's graph and injects it) before creating any Fragments; therefore, the Fragment's onAttach won't get a null Activity graph.

If we waited until onActivityCreated to do the injection, then the InjectingFragment-derived class wouldn't be able to use any injected dependencies in its onAttach override, because they wouldn't be injected yet.
